Repository josemarluedke/docfy, pull requests merged in 2021-03, with the labels that each got.

#80 Fix link from writing demos to writing markdown
  packages/docfy/package.json
  packages/ember/docs/writing-demos.md
Labels: Type: Documentation

#81 Use Glimmer component backing class rather than a templateOnly component
  packages/ember/docs/writing-demos.md
  packages/ember/src/index.ts
Labels: Type: Enhancement

#82 Upgrade remark-hbs to v0.4
  packages/core/package.json
  packages/ember/package.json
  yarn.lock
Labels: Type: Dependencies
