Repository josemarluedke/docfy, pull requests merged in 2021-01, with the labels that each got.

#61 [Ember] Move Demo Description before the actual example
  packages/@docfy/ember/src/plugins/utils.ts
  packages/@docfy/ember/tests/dummy/app/styles/app.css
  site/app/styles/docfy-demo.css
Labels: Type: Enhancement

#63 [Ember] Add demos to TOC
  packages/@docfy/core/src/-private/utils.ts
  packages/@docfy/core/src/plugins/toc.ts
  packages/@docfy/ember/src/plugins/extract-demos-to-components.ts
Labels: Type: Enhancement

#65 [Ember] Modify how demo title is rendered to match common markdown setup
  packages/@docfy/ember/addon/components/docfy-demo/description.hbs
  packages/@docfy/ember/tests/integration/components/docfy-demo/description-test.ts
Labels: Type: Enhancement

#68 fix a missing quote sign in the writing-demos.md
  packages/@docfy/ember/docs/writing-demos.md
Labels: Type: Documentation

#71 Add support for Ember rootURL
  packages/@docfy/ember/addon/components/docfy-link.ts
  packages/@docfy/ember/package.json
  packages/@docfy/ember/types/ember-get-config/index.d.ts
  yarn.lock
Labels: Type: Enhancement

#73 [Core] Remove unnecessary index
  packages/core/src/index.ts
  packages/core/src/plugins/index.ts
  packages/core/src/plugins/remove-unnecessary-index.ts
  packages/core/tests/__fixtures__/monorepo/packages/package1/components/form/something-else.md
  packages/core/tests/__snapshots__/generating-edit-url.test.ts.snap
  packages/core/tests/__snapshots__/headings-extraction.test.ts.snap
  packages/core/tests/__snapshots__/integration-nested-page-metadata.test.ts.snap
  packages/core/tests/__snapshots__/integration-remark-plugins.test.ts.snap
  packages/core/tests/__snapshots__/url-schema-auto.test.ts.snap
  packages/core/tests/__snapshots__/url-schema-manual.test.ts.snap
  packages/core/tests/integration-nested-page-metadata.test.ts
  packages/core/tests/url-schema-auto.test.ts
Labels: Type: Enhancement

#76 Upgrade Project Dependencies
  package.json
  packages/core/jest.config.js
  packages/core/package.json
  packages/ember/.eslintrc.js
  packages/ember/addon/components/docfy-demo.hbs
  packages/ember/addon/components/docfy-demo/example.hbs
  packages/ember/addon/components/docfy-demo/snippets.hbs
  packages/ember/addon/components/docfy-link.hbs
  packages/ember/addon/components/docfy-previous-and-next-page.hbs
  packages/ember/addon/components/docfy-previous-and-next-page.ts
  packages/ember/package.json
  packages/ember/tests/dummy/app/templates/application.hbs
  packages/ember/tests/dummy/app/templates/docs.hbs
  packages/ember/tests/index.html
  packages/ember/tests/test-helper.ts
  packages/plugin-with-prose/jest.config.js
  packages/plugin-with-prose/package.json
  site/app/components/page-headings.hbs
  site/app/components/sidebar-nav.hbs
  site/app/components/theme-switcher.hbs
  site/app/index.html
  site/app/templates/application.hbs
  site/app/templates/components/feature-card.hbs
  site/app/templates/docs.hbs
  site/app/templates/head.hbs
  site/package.json
  site/tests/index.html
  site/tests/test-helper.js
  yarn.lock
Labels: Type: Dependencies
